export const customStyles = {
  control: (styles) => ({
    ...styles,
    width: "100%",
    borderRadius: 0,
    fontSize: 14,
    lineHeight: "1.4rem",
    backgroundColor: "#f5f5f5",
    color: "#1a1a1a",
    cursor: "pointer",
    border: "none",
    boxShadow: "none",
    minHeight: 36,
    ":hover": { background: "#e8e8e8" },
  }),
  singleValue: (styles) => ({ ...styles, color: "#1a1a1a" }),
  input: (styles) => ({ ...styles, color: "#1a1a1a" }),
  option: (styles, { isFocused, isSelected }) => ({
    ...styles,
    fontSize: 14,
    lineHeight: "1.5rem",
    backgroundColor: isSelected ? "rgba(44,187,93,0.15)" : isFocused ? "#e8e8e8" : "#fff",
    color: isSelected ? "#2cbb5d" : "#1a1a1a",
    cursor: "pointer",
  }),
  menu: (styles) => ({
    ...styles,
    backgroundColor: "#fff",
    border: "1px solid #e0e0e0",
    borderRadius: 6,
    boxShadow: "0 8px 24px rgba(0,0,0,0.1)",
    marginTop: 2,
  }),
  placeholder: (styles) => ({ ...styles, color: "#1a1a1aaa", fontSize: 13 }),
  dropdownIndicator: (styles) => ({ ...styles, color: "#1a1a1aaa", padding: "0 8px" }),
  indicatorSeparator: () => ({ display: "none" }),
};
